name: CI / Automated Pull Request

on:
  push:
    branches-ignore:
      - "classic"
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create or Open A PR
        id: create-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          destination_branch: "classic"
          pr_title: "Hamster Left A Pull Request - (${{ github.event.head_commit.message }})"
          pr_body: "Details are on their way... - says Hamster."
          pr_reviewer: "offensive-vk"
          pr_label: "bot,automated,hamster,pull-request"
          pr_assignee: "TheHamsterBot"
          pr_draft: false
        continue-on-error: true

      - name: Save PR Number in ENV
        run: echo "PR_NUMBER=${{ steps.create-pr.outputs.pull-request-url }}" >> $GITHUB_ENV

  update_pr:
    needs: create_pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Pull Request Template
        run: |
          timestamp=$(date '+%b %d, %A %I:%M:%S %p')
          markdown=$(cat <<EOF
          ## This Pull Request Was Automated by [Hamster [bot]](https://github.com/TheHamsterBot)

          > [!NOTE]
          > Workflow Trigger: ${{ github.event_name }} event at ${{ env.HEAD_REF }} branch.
          > Details of Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

          - Author: @TheHamsterBot
          - Branch: ${{ github.base_ref }} (base) / ${{ github.head_ref}} (head)
          - Commit: ${{ github.sha }}
          - Workflow Path: ${{ github.workflow }}
          - Pull Request Number: #${{ github.event.pull_request.number || env.PR_NUMBER }}
          - Pusher Details: ${{ github.event.commits.author.name }} <${{ github.event.commits.author.email }}>

          ---

          Thanks.
          $timestamp
          Your Hamster 🐹 <code>PR90XPOMFW68FM</code>
          EOF)
          echo "$markdown" > .github/Auto_Pull_Request.md
          echo "MARKDOWN_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$markdown" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update Pull Request Body
        run: |
          gh pr edit "$PR_NUMBER" --body "$MARKDOWN_CONTENT"
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}