name: Automated Bulk Issue Creator

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
    inputs:
      issue_count:
        description: 'Number of Issues'
        required: true
        default: '100'

jobs:
  create_issue:
    runs-on: ubuntu-latest
    name: Workflow Job
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh -y
      - uses: actions/checkout@v4
      - name: Create Issues
        run: |
          # for i in $(seq 1 ${{ github.event.inputs.issue_count }}); do
          for i in $(seq 1 500); do
            issue_number=$(gh issue create --title "Automated Issue $i" --body "This is issue $i, created by Hamster [bot]." --label "automated,bot,hamster,issue" --assignee "TheHamsterBot")
            echo "Issue #$issue_number created."
            sleep 3
            gh issue close "$issue_number" --comment "Hamster [bot] - Closed This Issue."
            echo "Issue #$issue_number closed."
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}