name: Docker

on:
  schedule:
    - cron: '0 */1 * * *'
  push:
    branches: [ "classic", "**" ]
  pull_request:
    branches: [ "classic", "**" ]
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker Image
      run: docker build . --file Dockerfile -t classics:$(date +%s)