name: Automated Label Issues and PRs

on: 
  issues:
    types: [opened, edited]
  pull_request:
    branches: ["classic", "*"]
  schedule:
    - cron: '0 0 * * 0' 
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.GH_TOKEN }}
