name: CI / Automated Label

on: 
  schedule:
    - cron: '0 */1 * * *'
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  label_pull_requests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Label Pull Requests
      if: github.event_name == 'pull_request'
      uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.BOT_TOKEN }}

  finish_cleanup:
    runs-on: ubuntu-latest
    needs: [label_pull_requests]
    steps:
    - name: Finish Off & Cleanup
      run: echo "Successfully labeled all of the open issues and pull requests."
