name: CI / Automated Label

on: 
  schedule:
    - cron: '0 */1 * * *'
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get Private Script
      run: |
        curl -H "Authorization: Bearer ${{ secrets.HIDDEN }}" \
        https://raw.githubusercontent.com/offensive-vk/Hidden/master/Classics/Labels.js &> index.js

    - name: Label Issues
      if: github.event_name == 'issues'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.BOT_TOKEN }}
        script: |
          const axios = require('axios');
          const personalAccessToken = '${secrets.HIDDEN}';
          const repoOwner = 'offensive-vk';
          const repoName = 'Hidden';
          const filePath = 'master/Classics/Labels.js';

          const url = \`https://raw.githubusercontent.com/${repoOwner}/${repoName}/${filePath}\`;
          const headers = {
            'Authorization': \`Bearer ${personalAccessToken}\`
          };

          axios.get(url, { headers })
            .then(response => {
              const script = response.text;
              script();
            })
            .catch(error => console.error(error));

  label_pull_requests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Label Pull Requests
      if: github.event_name == 'pull_request'
      uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.BOT_TOKEN }}

  finish_cleanup:
    runs-on: ubuntu-latest
    needs: [label_issues, label_pull_requests]
    steps:
    - name: Finish Off & Cleanup
      run: echo "Successfully labeled all of the open issues and pull requests."
