name: Morning Maintenance

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Latest Updates
        run: git fetch --all; git pull --verbose

      - name: Send Greetings
        run: |
          echo "Howdy Everyone ! Wassup"
          echo "Good morning, contributors and watchers! Have a great day!"

      - name: Background Cleanup Job
        run: |
          sudo apt update -y; sudo apt install lolcat neofetch -y
          neofetch | lolcat 
          uname -a; whoami; df -T

  greetings:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        id: date_time
        run: |
          echo "DATE=$(date '+%B %d, %Y')" >> $GITHUB_ENV
          echo "TIME=$(date '+%I:%M %p')" >> $GITHUB_ENV

      - name: Say Good Morning
        run: |
          echo -e "\n# Good Morning, **General** ! \n\nToday is **${{ env.DATE }}** \n\n *Have a Wonderful Day Ahead.*" > GREETINGS.md

      - name: Commit & Push Changes
        run: |
          git config --global user.name "Hamster [bot]"
          git config --global user.email "TheHamsterBot@outlook.com"
          git add GREETINGS.md
          git commit -m "🤖 Hamster Sends Greeting of the Day."
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}