name: Morning Maintenance

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Latest Updates
        run: git fetch --all; git pull --verbose

      - name: Send Greetings
        run: |
          echo "Howdy Everyone ! Wassup"
          echo "Good morning, contributors and watchers! Have a great day!"

      - name: Background Cleanup Job
        run: |
          sudo apt update -y; sudo apt install lolcat neofetch -y
          neofetch | lolcat 
          uname -a; whoami; df -T