name: CI / Automated PR Manager

on:
  push:
    branches-ignore:
      - "classic"
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create or Open A PR
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "classic"
          pr_title: "Automated Pull Request by Actions Bot."
          pr_template: ".github/PR_BOT_TEMPLATE.md"
          pr_reviewer: "offensive-vk"
          pr_label: "bot,automated,unknown"
          pr_assignee: "npm-run-test"
          pr_draft: false