name: Stale Issues and PRs

on:
  schedule:
    - cron: '10 */1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      
    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-close: 7
          stale-issue-message: 'This issue seems to be inactive. If you believe its still relevant, please provide an update. Otherwise, it may be closed soon.'
          stale-pr-message: 'This pull request seems to be inactive. If you need further assistance or if there is any progress, please update the PR. Otherwise, it may be closed soon.'
          stale-issue-label: 'no-activity'
          stale-pr-label: 'no-activity'
          days-before-pr-stale: 3
          days-before-issue-stale: 3
          operations-per-run: 100